language: generic
      
   
services:
  - docker
          
git:
  depth: 3


jobs:
  include:
    - stage: Prepare mapping
      
      install:
      - npm install @rmlio/yarrrml-parser
      - cd obda/
      
      script: npx yarrrml-parser -i mapping.yaml -o mapping.ttl

    - stage: Whatever
      script: echo "ASDF"
