language: node_js
    
 
services:
  - docker
        
git:
  depth:       3
node_js:
  - "node"

install:
- npm install @rmlio/yarrrml-parser

before_script:
- cd obda/
- npx yarrrml-parser mapping.yaml mapping.ttl 


script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email:       false
