jobs:

  language: generic
      
   
  services:
    - docker
          
  git:
    depth:       3
  node_js:
    - "node"

  install:
  - npm install @rmlio/yarrrml-parser

  before_script:
  - cd obda/
  - npx yarrrml-parser -i mapping.yaml -o mapping.ttl

  script: true

  notifications:
    email:       false
